baseURL = 'https://nairjayesh.github.io/'
languageCode = 'en-us'
title = 'Jayesh Nair'

[params]
  description = "Personal website of Jayesh Nair"

[markup.goldmark.renderer]
  unsafe = true  # Allows HTML in markdown

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true  # Set this to TRUE to work with the CSS above

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/writings/"
    weight = 3
  [[menu.main]]
    name = "Tech"
    url = "/notes/"
    weight = 4
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5
  [[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 6
  [[menu.main]]
    name = "Excerpts"
    url = "/excerpts/"
    weight = 7
  # ... other menu items

  [module]
  [[module.imports]]
    path = "github.com/nairjayesh/find-transcripts"

